### ISSUE TITLE
cygwin64生成的秒传代码，不能显示完成

### ISSUE THREAD

**Issue by geminijummnm** [qianbinbin/miaochuan#4]
cygwin64生成的秒传代码，不能显示完成，当文件过多时，生成的秒传会因为终端的显示无法完整显示，能不能添加命令输出到json文件最好可以设置支持韩语字符

**Comment by qianbinbin** [comment]
```sh
$ miaochuan.sh file.tar >out.txt
```

**Comment by qianbinbin** [comment]
1. 不能完整显示的应该查看你的终端设置，或按照上面的方法重定向到文件
2. json 文件不知道是什么需求，没见过使用这种格式的脚本
3. 语言相关的设置也与脚本无关
